# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.04.060647'

RELEASE_GIT_HEAD = '4e7c1ea346b510280218b47e8653dbbca3a69870'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'nicolaasjan/yt-dlp'

ORIGIN = 'nicolaasjan/yt-dlp'

_pkg_version = '2025.06.04.060647'
