# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.20.172830'

RELEASE_GIT_HEAD = 'e3b42d8b1b8bcfff7ba146c19fc3f6f6ba843cea'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'nicolaasjan/yt-dlp'

ORIGIN = 'nicolaasjan/yt-dlp'

_pkg_version = '2024.04.20.172830'
