# Autogenerated by devscripts/update-version.py

__version__ = '2024.05.06.055244'

RELEASE_GIT_HEAD = '5904853ae5788509fdc4892cb7ecdfa9ae7f78e6'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'nicolaasjan/yt-dlp'

ORIGIN = 'nicolaasjan/yt-dlp'

_pkg_version = '2024.05.06.055244'
